import PDFDocument from "pdfkit"

export const generatePdf=async (data) => {
    //return promise
    return new Promise((resolve,reject)=>{
        const doc=new PDFDocument({
            size:"A4",
            margin:50,
            info:{
                Author:"SynthAI",
                Title:data.title,
                Creator:"SynthAI"
            }
        })

        //chunk array
        const chunks=[]

        //3 events of doc ->data,end,error
        doc.on("data",(chunk)=>chunks.push(chunk))

        //concatenate all small chunks of buffer
        //end event --means-- doc is created -->Promise resolve
        doc.on("end",()=>resolve(Buffer.concat(chunks)))

        //if error comes during doc creation
        doc.on("error",()=>reject)

        //title
        doc
            .fontSize(28)
            .text(data.title,{
                align:"center"
            })
            .fillColor("#111827")
        
        //space
        if(data.subtitle) {
            doc.moveDown(0.5)
        }
        
        //subtitle
        doc
            .fontSize(12)
            .text(data.subtitle,{
                align:"center"
            })
            .fillColor("#6B7280")
        
        doc.moveDown(2)

        //sections
        data?.sections?.forEach(s => {
            doc
                .fontSize(18)
                .text(s.heading)
                .fillColor("#111827")

            doc.moveDown(0.5)

            //points
            s?.points?.forEach((p)=>{
                doc
                    .fontSize(12)
                    .text("• " + p, {
                        lineGap: 5
                    })
                    .fillColor("#374151")
            })

            doc.moveDown()

        })

        doc.moveDown()

        //footer
        doc
            .fontSize(10)
            .text("Generated By SynthAI",{
                align:"center"
            })
            .fillColor("#9CA3AF")
        
        doc.end()
    })
}